:repository-owner: arduino-libraries
:repository-name: MKRIMU

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

Allows you to read the acceleration, gyroscope, magnetic fields and Euler angles from the IMU on your MKR IMU Shield.

  You can also set an interrupt on AnyMotion in XYZ dir and react with your routine.
  To do so your sketch have to:

  #include "ArduinoLowPower.h"
  #include "MKRIMU.h"
  #include <SPI.h>
  const byte interruptPin = 0;
  volatile bool intFlag=false;

  in setup:
  ...
  pinMode(interruptPin, INPUT_PULLUP);
  LowPower.attachInterruptWakeup(digitalPinToInterrupt(interruptPin), dummy, RISING);
  ...
  IMU.begin();
  IMU.setInterrupt();
  ...

  void dummy() 
  {
    intFlag = true;
  }

  in loop:
  ...
  if (intFlag) 
  {
    do ypur routine
    IMU.resetInterrupt(); // to continue getting other interrupts
    intFlag = false;
  }
